[package]
name = "kafka-bombardier"
version = "0.1.0"
authors = ["gauravsaini"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdkafka = "0.23.1"
clap = "2.33.1"
rayon = "1.3.0"
